version: '3.8'

services:
  hadoop:
    image: apache/hadoop:3.3.6
    container_name: hadoop
    user: root
    restart: always
    ports:
      - "9870:9870"   # Web UI for NameNode
      - "9864:9864"   # DataNode UI
      - "9000:9000"   # HDFS port
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
    command: /bin/bash -c "service ssh start; hdfs namenode -format; start-dfs.sh && tail -f /dev/null"
    volumes:
      - hdfs_data:/hadoop/dfs

volumes:
  hdfs_data:
